# Generated by Django 5.1.3 on 2024-12-06 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expense', '0002_expense'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='payment_method',
            field=models.CharField(choices=[(None, 'Select'), ('UPI', 'UPI'), ('Card', 'Card'), ('Cash', 'Cash')], default='Select', max_length=100),
        ),
        migrations.AlterField(
            model_name='expense',
            name='category',
            field=models.CharField(choices=[(None, 'Select'), ('Housing', 'Housing'), ('Transportation', 'Transportation'), ('Food', 'Food'), ('Healthcare', 'Healthcare'), ('Education', 'Education'), ('Entertainment', 'Entertainment'), ('Personal Care', 'Personal Care'), ('Debt Payments', 'Debt Payments'), ('Savings & Investments', 'Savings & Investments'), ('Gifts & Donations', 'Gifts & Donations'), ('Insurance', 'Insurance'), ('Travel', 'Travel'), ('Miscellaneous', 'Miscellaneous')], default='Select', max_length=100),
        ),
    ]
